// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eemhtaaczkwyluokgldj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlbWh0YWFjemt3eWx1b2tnbGRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1Mjk4OTMsImV4cCI6MjA3MzEwNTg5M30.04fUDZTdsu8U8UUqZKbihT3F5v0w_lWh9wGKXBm_itI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});